[workspace]
members = [
  "http-api",
  "org-node",
  "git-server",
  "shared",
]

[patch.crates-io.radicle-daemon]
git = "https://github.com/radicle-dev/radicle-link"
rev = "2df248a8e077d02cbb075da073dbe7ab9e282a70"

[patch.crates-io.librad]
git = "https://github.com/radicle-dev/radicle-link"
rev = "2df248a8e077d02cbb075da073dbe7ab9e282a70"

[patch.crates-io.ethers]
git = "https://github.com/gakonst/ethers-rs"
branch = "master"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/FintanH/thrussh.git"
branch = "generic-agent"

[profile.release]
debug = true
